### PR TITLE
Set local dummy data

### LINKED ISSUE #530: Use workspace generator to add dummy local data
## Description
Since sync is not working yet I think it might come useful to have a bunch of local data to use for developing and debugging the UI. We can use the workspace generator for this and basically replace the text files in Assets/textfiles with whatever it generates.

Then we'll need to touch a bit the Repository so we can easily swap this mock version with the live one. (Repository.live and Repository.mock like the Pointfree guys do seems reasonable enough)

This will come handy not only on this early stages of development but also when ever we want to debug with specific data or when we don't have an internet connection.

## Definition of done
- [ ] The files in Assets/textfiles are replaced with the info generated by the workspace generator
- [ ] This mock version is easily swappable with the live one

### PR DESCRIPTION
**Pull request by Odrakir**
## Info
Sets data extracted from the Workspace generator as local JSON files to test the app.

### Summary
This just replaces the content of the JSON files in the assets with data from the workspace generator and then makes some changes in the repository so that data is fetched on fresh installs.

If you want to use this data just delete the app and install it again. If the DB is empty it'll get the data from those dummy files. Feel free to modify that data or create new copies to test different things.

### Relationships
Closes #530 

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

- [ ] The code used custom templates

### Review template
As mentioned above, delete the app and install again for it to use the dummy data.

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
Go!

### CODE REVIEW

File: Modules/Repository/Repository/Repository.swift [hunk 1]
```diff
@@ -50,26 +42,92 @@ extension Repository: TimeLogRepository {
...
+
+                return Single.just(workspaces)
+            }
     }
     
     public func getClients() -> Single<[Client]> {
         database.clients.rx.getAll()
+            .flatMap { clients in
+                if clients.count == 0 {
+                    return self.api.loadClients()
```
Comment (heytherewill) [inline Modules/Repository/Repository/Repository.swift:62]: I really don't like the inclusion of an API here. It's misleading, since this api will never be called with actual data. Why not mock the entire repository instead?

Comment (Odrakir) [reply Modules/Repository/Repository/Repository.swift]: Take another look, I subclassed the Repository. Also I've called this version of the environment `local` rather than `mock`, since I think it better reflects how it works: the database and time services are the live ones, but the API takes the data from local files. We could further create other versions of the environment for different purposes.
