### PR TITLE
Fix some app inconsistencies

### LINKED ISSUE #523: Catch up on app translations
## Description
We need to catch up on translations and stop using hardcoded strings

## Definition of done
- [ ] All hardcoded strings are removed from the app
- [ ] These strings are moved to the resources and properly translated

### LINKED ISSUE #524: Stop including running time entries in the log
## Description
The running time entry should not be included in the log, ever.

## Definition of done
- [ ] The running time entry is not included in the main log

### PR DESCRIPTION
**Pull request by heytherewill**
### Summary
This fixes some inconsistencies in the codebase, namely:

- It removes the running entry from the main log
- It extracts all hardcoded strings, putting them into a localizable file
- It removes the iOS13 icons, to remove warnings 
- It changes the layout of the main log so that the description is centered when there's no project
- It changes the layout of the suggestions so that the description is centered when there's no project
- It changes the assets for the running entry card to use proper buttons

### Relationships
Closes #523
Closes #524

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

- [ ] The code used custom templates

### Pointers
Go for it commit by commit. Do make a functional test.

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones
- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
Anyone, anytime

### CODE REVIEW

File: Modules/Assets/Assets/Extensions/Strings.swift [hunk 1]
```diff
@@ -7,10 +7,21 @@ public struct Strings {
...
+    public static func create(project: String) -> String {
+        return "\("createProject".localized) \(project)"
+    }
+    
+    public static func create(tag: String) -> String {
+        return "\("createTag".localized) \(tag)"
+    }
+    
+    public static var today: String { "yesterday".localized }
+    public static var yesterday: String { "today".localized }
```
Comment (sofokli1) [inline Modules/Assets/Assets/Extensions/Strings.swift:19]: these 2 need swapping

Comment (sofokli1) [inline Modules/Assets/Assets/Extensions/Strings.swift:19]:
```suggestion
    public static var today: String { "today".localized }
    public static var yesterday: String { "yesterday".localized }
```

File: Modules/Timer/Timer/TimeEntriesLog/Views/TimeEntryCell.swift [hunk 2]
```diff
@@ -22,4 +23,9 @@ class TimeEntryCell: UITableViewCell {
 
         // Configure the view for the selected state
     }
+    
+    override func layoutSubviews() {
+        super.layoutSubviews()
+        _ = containerView.roundedCorners()
```
[the remark this answers is not in the document]
Comment (Odrakir) [reply Modules/Timer/Timer/TimeEntriesLog/Views/TimeEntryCell.swift:29]: @dshr clarified to me the intention of this was to make those methods chainable. Maybe we can then add @discardableResult to it so we don't have to do the `_ = ...`
